### ISSUE TITLE
Invalid error when saving plugin settings

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#105]
When plugin settings are changed, even though they are correctly saved to the database in the interface an "Error:DB Connection Failed" shows up, as per the below screenshot.

![image](https://cloud.githubusercontent.com/assets/3965050/8474575/f900278e-20a8-11e5-8e7f-74f4f495b7a3.png)

**Comment by carmelopreeostudios** [comment]
Fixed commit ab860107e707635446d4683c8eaf71c74f24dd9b
