### ISSUE TITLE
db table creation error

### ISSUE THREAD

**Issue by fotomut** [WPWhiteSecurity/WP-Security-Audit-Log#113]
I'm getting many db errors because `wp_wsal_options` table was never created.  The very first error is 
```
[08-Jul-2015 15:55:01 UTC] WordPress database error COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4' for query CREATE TABLE wp_wsal_options (
    id BIGINT NOT NULL AUTO_INCREMENT,
    option_name VARCHAR(100) NOT NULL,
    option_value TEXT NOT NULL,
    PRIMARY KEY  (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8_general_ci made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, WpSecurityAuditLog->Load, WSAL_DB_ActiveRecord->Install, dbDelta
```

I noticed other database related issues here and wanted to share mine.  This is a brand new install of v1.6.1 using the WordPress plugin repository.

**Comment by WPWhiteSecurity** [comment]
Hello fotomut,

Thank you for showing interest in our plugin. Most of the issues you see here are pre-release issues which are discovered during testing. "support" issues are typically reported here:

https://wordpress.org/support/plugin/wp-security-audit-log

Regarding your issue, please note that next week we are releasing a new version of the plugin which has got a completely new database connector so can you please wait till next week? If you would like to beta test the plugin drop us an email on plugins@wpwhitesecurity.com.

Thank you.
