### ISSUE TITLE
Missing Text from Translations

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#12]
The German translator pointed out that the following are missing from the translating text. Can you please fix?

![1](https://cloud.githubusercontent.com/assets/3965050/4699579/aec57504-5842-11e4-9076-17c2f1053caf.png)

![2](https://cloud.githubusercontent.com/assets/3965050/4699581/b36d2caa-5842-11e4-8b4b-a1efd3558bcf.png)

![3](https://cloud.githubusercontent.com/assets/3965050/4699582/b8b314cc-5842-11e4-891a-5ed23a2eb94e.png)

![4](https://cloud.githubusercontent.com/assets/3965050/4699583/b8d25d82-5842-11e4-9ddd-ff6e54316ee1.png)

![5](https://cloud.githubusercontent.com/assets/3965050/4699584/b8fcfda8-5842-11e4-9fad-94bf5c043bf5.png)

![6](https://cloud.githubusercontent.com/assets/3965050/4699585/b90dc44e-5842-11e4-99e8-3220cf6c2062.png)

**Comment by WPWhiteSecurity** [comment]
closing this issue.
