### ISSUE TITLE
Deleting of custom field from Page generates wrong alert

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#130]
When a custom field is deleted from a page the following alert is generated: 2055 (deleted custom field from blog post)

Alert 2061 should be reported (deleted custom field from page)

**Comment by carmelopreeostudios** [comment]
I noticed that every page is considered to be a post by wordpress (for custom fields) so I get type "post" even when updating a page. Not sure on way forward yet.

**Comment by WPWhiteSecurity** [comment]
@carmelopreeostudios correct but there are ways how to recognize if it is a page or not. I mean other alerts, e.g. creating of custom field in a page work correctly so we should be able to do it when deleting it, no?

**Comment by WPWhiteSecurity** [comment]
fixed in 2.1 branch, well done
