### ISSUE TITLE
Track Admin Page Views for HIPAA

### ISSUE THREAD

**Issue by jb510** [WPWhiteSecurity/WP-Security-Audit-Log#132]
HIPAA's hard to interpret, but at least as I read it we're supposed to track not just create/update/delete, but also page views of ePHI.

ie. I need to know if an admin LOOKED at a user profile, or looked at the CPT that holds ePHI info for that user.

Is there any way to track wp-admin page views with WPSAL? If not, what about adding something to do that or facilitate that?

**Comment by WPWhiteSecurity** [comment]
Hello jb510,

Thank you for the recommendation. We added this feature request to our to do list though at this stage cannot give you any actual ETA when such feature will be available. If you need further information or would like to get in touch, send us an email on plugins@wpwhitesecurity.com.
