### ISSUE TITLE
Incorrect Alert when Contributor Submits article for Review

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#147]
A user with contributor role cannot publish articles, but can only submit them for review. And when a contributor submits an article for review alert 2001 (published article) is shown, which is incorrect.

In such situation we should report the following alert:

ID: 2071
Severity: NOTICE
Text: Submitted blog post %Post Title% for review. Blog post ID is %ID%

**Comment by carmelopreeostudios** [comment]
@robert81 I changed the alert code to 2073, because 2071 is used for widget position

**Comment by WPWhiteSecurity** [comment]
My bad again. It is working. Sorry for the false alarm.
