### ISSUE TITLE
Incorrect Alerts for Premium Add-ons

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#180]
I have documented all the alerts for the premium add-ons in the roadmap. Please refer to the roadmap document to finalize.

**Comment by robert81** [comment]
Almost there. We skipped one instruction:

These alerts should have a different background colour (R213 G228 B110) <- I am not sure of this colour. I am looking for something that stands out from the other alerts so let me know what you think could be the best colour.
