### ISSUE TITLE
SQL Error with revision link after 4.4 upgrade

### ISSUE THREAD

**Issue by steveturri** [WPWhiteSecurity/WP-Security-Audit-Log#181]
After upgrading to 4.4 when we make some revisions it is failing to update the audit log it seems.
WordPress database error: [Column 'value' cannot be null]
REPLACE INTO 'wp_wsal_metadata' ('id', 'occurence_id', 'name', 'value') VALUES (0, 4844, 'RevisionLink', NULL)

![security_audit_log_issue](https://cloud.githubusercontent.com/assets/2520418/11826994/22dc2df8-a346-11e5-8235-f70763e0eb4e.PNG)

**Comment by WPWhiteSecurity** [comment]
@steveturri thank you for reporting this. We can confirm we identified the issue and a fix will be available in the upcoming version of the plugin. We are trying to release before he festive season.
