### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'Alert with code "5001" Upon installing Plugin

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#23]
Upon installing the plugin a PHP Fatal error for alert code 5001 is always generated. As a matter of fact when the plugin itself is activated the alert "5001 plugin is activated" is not generated. I presume we can fix this by "improving" the order of when the sensors / alerts are registered prior to activating the plugin.

**Comment by uuf6429** [comment]
I'm not sure where this is coming from, I haven't been able to replicate the issue.
I can "force" it to always show this alert upon installation (by faking the event), if we want this feature...but it wouldn't fix the problem you're describing.

**Comment by robert81** [comment]
Unfortunately this issue still persists. Let's do a remote session when you can so we can see it.

**Comment by robert81** [comment]
Once you will be reviewing the activation process (to fix issue #40 might as well look into this.
