### ISSUE TITLE
Promotional Alerts are not showing in the Audit Trail

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#262]
The promotional Alerts are not showing in the Audit trial.

**Comment by carmelopreeostudios** [comment]
@robert81 I understood that the promotional alerts don't show if the user active at least one add-on

**Comment by WPWhiteSecurity** [comment]
@carmelopreeostudios correct but I was testing the plugin in a new WordPress install, without any add-ons etc and a fresh install of WordPress, hence the promotional alerts should show.
