### ISSUE TITLE
Incorrect user in Alert 2099 - Posted a comment

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#269]
When a logged in user posts a comment the user is **website visitor**. When a logged in user posts a comment the user should be the actual user.**Website visitor** should be used when a non logged in user posts a comment.

Also the 2099 Alert text is wrong as shown in the below:

![image](https://cloud.githubusercontent.com/assets/9016202/16608429/9ced4760-4343-11e6-895b-58fd0061fe44.png)

The text should be:

Posted a comment in response to [post title] on [date/time]

**Comment by carmelopreeostudios** [comment]
@robert81 I don't understand which messages I have to use for comment alerts, I followed exactly the Roadmap. Before It was with "in response to [post title]" and after you removed that part. Should I add that part for all the comment's messages?

**Comment by carmelopreeostudios** [comment]
@robert81 [here ](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/258) 2099 is missing

**Comment by WPWhiteSecurity** [comment]
@carmelopreeostudios My fault. Ok here is the finalized list then including 2099: #258 

Note that there are 2 different 2099 alerts. Thank you.
