### ISSUE TITLE
Problem with Plugin and Admin restriction option

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#329]
If the user enabling the plugin option **Restrict Plugin Access** is already added in the **Can Manage Plugin** when activating the setting, that user and all other administrators will be locked out.

Issue reported here: https://wordpress.org/support/topic/sorry-you-are-not-allowed-to-access-this-page-9/#post-8260822

**Comment by robert81** [comment]
There is still a problem with this option. All the fix does is clears the list of users in the Can Manage Plugin to avoid conflicts. As explained in the help text of the option, when this option is enabled **All administrators who are not listed in Can Manage or Can View audit log** should be restricted access.
