### ISSUE TITLE
Timezones and formats in Multisite

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#333]
This is more of a question, just to confirm functionality:

It seems that on multisite, on the network dashboard the date format is mm-dd-yyyy, the time zone is UTC and the time format is 24 hours.

Is this the default used when there is no timezone specified? I am asking since WordPress does not have any date / time configuration on the network dashboard but only sub sites can be configured.

If so, whenever we cannot read such properties (like in multisite since they are not available) the defaults should be so:

mm-dd-yyyy
24 hours clock
UTC

**Comment by carmelopreeostudios** [comment]
@robert81 The default format of Wordpress is **F j, Y g:i a** and we have it for each site (date and time format are always available).
About the timezone we have two options:
- the one of Wordpress
- the one of the server
