### ISSUE TITLE
Failed Logins Issue (Specific Alert 1003 issue) with Multisite

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#34]
In a multisite environment alert 1003 is not "working correctly". This is what is happening:

Setup: 3 websites on a multisite:

site1.multiwp.com
site2.multiwp.com
site3.multiwp.com

There are a number failed logins for a non existing user from host 192.168.2.127 hence Alert 1003 is generated reporting the site name, as per the below screenshot:

![image](https://cloud.githubusercontent.com/assets/3965050/6164565/c577b38a-b2a0-11e4-9064-31b5dd2d7bba.png)

If failed logins for a non existing user are generated from the same host but on a different site, e.g. site2.multiwp.com the date of the same Alert 1003 is being updated. In the case of multisite we need to keep track of failed logins specifically for each site on the network hence in the above case a new Alert 1003 should have been generated for site2.

**Comment by carmelopreeostudios** [comment]
@robert81 Fixed

**Comment by robert81** [comment]
@carmelopreeostudios the above issue is fixed now though it created another issue, the 10+ limit is no longer working and the plugin is now recording each failed login to the database. Check the screenshot below, it applies to both single site and multisite installation.

![image](https://cloud.githubusercontent.com/assets/3965050/6173573/5477cd70-b2e9-11e4-875f-06b6b8f7a247.png)

Once we reach 10+ failed logins for a specific criteria the plugin should continue checking the login ids but if that criteria has reached 10+ the plugin should not write to database.

**Comment by markdelf** [comment]
@carmelopreeostudios let's try to test more before we mark an issue as fixed. Also when you commit we can write "Fixes #number-of-issue" and it would add a comment here for you automatically.

**Comment by robert81** [comment]
@carmelopreeostudios this is the last issue for the release of 1.4. Hence can you please focus on this as next task? Thanks a lot.

**Comment by carmelopreeostudios** [comment]
@robert81 The plugin continued to record because for testing I changed the limit number,
now is fixed
commit 986a6489b0fa4d99e1ec5280da856801363acf1b

**Comment by robert81** [comment]
@carmelopreeostudios There are still issues with the failed logins alerts, this time with Alert 1002 (failed login for existing user). When there are 13 (collectively) 1002 alerts no more alerts are being reported even if the users are different. As per the below screenshot there are:

9 * 1002 alerts for user ruby
4 *1002 alerts for user site1

If there are any further failed logins for any of the above mentioned users, or for any other existing user in such case no alerts 1002 are generated.

![image](https://cloud.githubusercontent.com/assets/3965050/6236873/7e187630-b6ee-11e4-9732-a10e689329dd.png)

**Comment by carmelopreeostudios** [comment]
@robert81 I have tested all the different cases with (site id, ip and user), I register the alert for each case 11 times and after I ignore it.

**Comment by robert81** [comment]
Working fine, though there is a minor issue I am opening a ticket for.
