### ISSUE TITLE
Plugin Settings Need to Be Generated Upon Install

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#35]
The plugin settings in the WordPress option table, such as "wsal-pruning-date" are not generated during install but only generated once the user accesses the plugin's settings the first time. Such settings should be created upon install, hence during an activation the plugin should:

1. Check if there are the settings specified already

2. If they are specified it should check that ALL settings are there. If any are missing they should be populated with the default values

3. If it finds no settings at all it should generate them with the default settings the plugin is shipped with.

**Comment by carmelopreeostudios** [comment]
Default config generated on the installation and checking if is on the wp-config table already,
for the follow fields:
wsal-pruning-date, wsal-pruning-limit-e, wsal-pruning-limit

even for multisite, added removal setting on uninstall
