### ISSUE TITLE
IP Address not being retrieved in specific scenarios

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#36]
As explained over email there are some specific scenarios where the IP address is not being populated in the alerts, instead "unkown" is shown. 

Please advise what information you need from the users to allow us to troubleshoot this issue.

**Comment by markdelf** [comment]
@robert81 pasting some research below;

AuditLogListView.php line 186:

```
$scip = $item->GetSourceIP();
$oips = array(); //$item->GetOtherIPs();
// if there's no IP...
if (is_null($scip) || $scip == '') return '<i>unknown</i>';
```

Meta value client ip appears to be null in database. So we need to investigate when this is being stored. This takes us back to Settings.php line 440 function GetMainClientIP

```
	public function GetMainClientIP(){
		$result = null;
		if ($this->IsMainIPFromProxy()) {
			// TODO the algorithm below just gets the first IP in the list...we might want to make this more intelligent somehow
			$result = $this->GetClientIPs();
			$result = reset($result);
			$result = isset($result[0]) ? $result[0] : null;
		} elseif(isset($_SERVER['REMOTE_ADDR'])) {
			$result = $this->NormalizeIP($_SERVER['REMOTE_ADDR']);
			if (!$this->ValidateIP($result)) $result = null;
		}
		return $result;
	}
```

The below are the two scenarios where in IP is **not** stored ("unknown"):

* If isMainIpFromProxy returns false and REMOTE_ADDR is not set we would get null; then ip is not stored.

*If isMainIpFromProxy returns false and REMOTE_ADDRESS is set we normalize the ip address and then check whether it is valid or not. if the ip is not valid, result would be null; then the ip is also not stored.

Validate IP checks the following, which is most likely the case for the unknowns;

```
	protected function ValidateIP($ip){
		$opts = FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6;
		if ($this->IsInternalIPsFiltered()) $opts = $opts | FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE;
		return filter_var($ip, FILTER_VALIDATE_IP, $opts);
	}
```

Note:
*Note that the filter_var() function requires at least PHP version 5.2.0. It is included by default with versions >= 5.2.0*

**Comment by robert81** [comment]
As discussed let's troubleshoot this step by step. The first task we need to work on is the following:

If the validation fails, rather than reporting unkown IP the plugin should report IP is not valid.

**Comment by markdelf** [comment]
@robert81 see my commit above. If you could kindly test that nothing breaks (since you won't be able to replicate the issue).

**Comment by robert81** [comment]
@markdelf Testing this and so far nothing breaks. In the meantime I will leave this issue open until we sort out the problem of the users. Notes:

1. This small fix should be included in 1.4.
2. Users are running versions 5.3 and later on their environment, confirmed. In fact with the previous version everything was working for them, it just stopped working when they upgraded to 1.3.3.

**Comment by robert81** [comment]
One of the users has updated to version 1.4 and now is getting the following error instead of unknown:

Error 901: Invalid IP Address

Screenshot attached for more reference:

![image](https://cloud.githubusercontent.com/assets/3965050/6351767/806c9b5a-bc3e-11e4-8be7-7d0cd8929700.png)

**Comment by markdelf** [comment]
Ok so now we know that the validateIp function is definitely returning not valid for his IP. 

The are the lines we are interested in:

```php
  protected function ValidateIP($ip){
        $opts = FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6;
        if ($this->IsInternalIPsFiltered()) $opts = $opts | FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE;
        return filter_var($ip, FILTER_VALIDATE_IP, $opts);
    }
```

**Comment by robert81** [comment]
Ok good. Does the error code state something in particular though? As in what is the way forward?

**Comment by markdelf** [comment]
No it's a custom error code that we had agreed to add (show) instead of 'Unknown IP address'.

I'm still not sure on the way forward but it does tell us that the $ip address we are trying to validate in this case is NOT a valid ip4/ipv6 address. Will think on best way forward

```php
if (!$this->ValidateIP($result)) {
$result = "Error " . self::ERROR_CODE_INVALID_IP . ": Invalid IP Address";
}
```

**Comment by robert81** [comment]
OK. Considering the users are very responsive and willing to help maybe we could add some debugging to capture and log the IP address prior to it being validated, hence we can get a better idea of what is exactly happening. We can send the build to the user, ask him to reproduce the issue and get the logs from him.

**Comment by robert81** [comment]
Another user who reported the same issue is not getting an error, no IPs seem to be recorded as per the below screenshot:

![20150303182112](https://cloud.githubusercontent.com/assets/3965050/6471198/610adece-c1e9-11e4-90a9-1d646663eeef.png)

**Comment by robert81** [comment]
@carmelopreeostudios @markdelf sent you the first copy of the logs via email.

**Comment by markdelf** [comment]
I've run the same exact code on my machine with the same IP address and it says valid IP for me;

```php
<?php

function ValidateIP($ip){
    $opts = FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6;
    //$opts = $opts | FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE;
    return filter_var($ip, FILTER_VALIDATE_IP, $opts);
}

$ip = "71.206.233.178";
if (!filter_var($ip, FILTER_VALIDATE_IP) === false) {
    echo("$ip is a valid IP address");
} else {
    echo("$ip is not a valid IP address");
}
echo "<br />";

print_r(ValidateIP($ip));
?>
```

I'm using both FILTER_VALIDATE_IP directly and even the same function we have in the plugin. Both validate ok. 

Output from the above:

```
71.206.233.178 is a valid IP address
71.206.233.178
```

Need to research more but so far everything seems to indicate towards configuration issue on their setup.

**Comment by joseforland** [comment]
Robert, any idea what's the PHP Version the user got the problem? (also, can you forward the logs to me too?)

Managed to find that the example Mark used, only returns "valid" from PHP 5.3.10 onwards.  All PHP Versions from 5.2 (when it was available) to 5.3.3 return false.

**Comment by robert81** [comment]
@joseforland just forwarded you the logs and very good catch.

So far 3 users have reported the problem. I do not know what version of PHP the user who provided the logs is running but the other 2 are running 5.3.3.  So this might be the issue. So I presume we need to find out why it is failing.

P.S. The plugin should be installed on systems using 5.3 and onwards. If someone tries to install the plugin on a 5.2 system the plugin won't install.

**Comment by robert81** [comment]
@joseforland @carmelopreeostudios @markdelf The guy who provided the logs is running WordPress on PHP 5.3.2-1.

As Josef pointed out it seems that the PHP version is the issue at this stage.

**Comment by joseforland** [comment]
Great that we found where the problem is.  Now I think that we have 2 options:

1. Update the code & include a custom function validation of an IP Address using regex
2. Indicate the users to upgrade PHP to at least 5.3.10

Let us know with which one you want to go ahead Robert

**Comment by robert81** [comment]
@joseforland thanks for the troubleshooting. We should go with option 1 because even though we have a minimum requirement of 5.3, WordPress supports much older versions (unfortunately) so I don't want to make it even harder than it is now.

Can we please update branch 1.4.1 with the fix so first I send it to the users who reported the issue so they can test it out?

Thanks
