### ISSUE TITLE
Refresh Audit View Setting not working

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#37]
By default the Refresh Audit View option is set to automatic. Though it is impossible to switch if off, i.e. once you try and save the settings the option is reverted back to automatic. 

Please also update the text of this setting with the below:

Option name: Refresh Audit Log Viewer
Option-value-1: Automatic  — Refresh Audit Log Viewer as soon as there are new alerts.
Option-value-2: Manual  — Refresh Audit Log Viewer only when the page is reloaded.

**Comment by carmelopreeostudios** [comment]
@robert81 This is fixed
