### ISSUE TITLE
Alert 1006 is not being generated

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#386]
When a user logs out all other sessions from the profile page, Alert 1006 is not being generated.

**Comment by carmelopreeostudios** [comment]
@WPWhiteSecurity this alert is triggered in the **Users Sessions & management** plugin, when the user press "Destroy session" for **all** the session of the same user.
I don't see in the profile page this functionality

**Comment by WPWhiteSecurity** [comment]
@carmelopreeostudios when a user has multiple logged in sessions, the highlighted button below is enabled in a user's WordPress profile.

![image](https://cloud.githubusercontent.com/assets/9016202/24883528/2ae1d098-1e3d-11e7-9fdf-fb384c9e026e.png)

When the user clicks such button to log out all other sessions, such action should be reported in the audit log with Alert 1006.

**Comment by carmelopreeostudios** [comment]
@WPWhiteSecurity that section is enabled when you install an other plugin, **not in Wordpress**.
If you want trigger event on that plugin we can

**Comment by WPWhiteSecurity** [comment]
@carmelopreeostudios that feature is available in a default WordPress install. It has been there since 4.1.
