### ISSUE TITLE
Alert 4002 (Change of user role) Still generated when user is excluded

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#41]
Scenario: user "admin" and role "administrator" are excluded.

When "admin" with administrator role changes the role of another user from administrator to author, the plugin still creates Alert 4002 (User role change) even though the user doing the change is excluded from monitoring.

This could be related to the fact that the author role is being used in the alert.

**Comment by carmelopreeostudios** [comment]
Fixed, Checking the user who changes the role
