### ISSUE TITLE
Incorrect alert reported when excluded user creates a new user

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#42]
Normal scenario: when user "admin" creates a new username "kypri" with the role of "author" the following alert is created:

ID: 4001
User: admin
message: Created a new user kypri with the role of administrator

Though if the "admin" user is excluded from monitoring, rather than no alerts the following alert is being reported:

ID: 4002
User: admin
message: Changed the role of user kypry from to administrator

In such case no alerts should be created. This issue is related to the previous 4002 issue because of the way WordPress works, hence most probably when #41 is fixed this will be fixed as well.

**Comment by carmelopreeostudios** [comment]
Yes, is the same problem of #41
