### ISSUE TITLE
Remove Mcrypt completely

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#425]
At the moment Mcrypt is being used to ensure existing customers who use external DB for archiving etc can upgrade. Mcrypt completely after a few updates.

**Comment by asharirfan** [comment]
@WPWhiteSecurity I have already removed it entirely in `3.2.3.3` update. You can check the changelog to confirm.

**Comment by WPWhiteSecurity** [comment]
Yes @asharirfan I was pretty sure we had removed it though since the ticket was still open thought of listing it, just in case. Thanks.
