### ISSUE TITLE
New exclude input fields cccept any value / Implement auto complete

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#43]
The new input fields in the settings, mainly:

Excluded Users
Excluded Roles
Excluded Custom Fields

Such behaviour can potentially lead to a lot of problems. In the case of Excluded Users and Excluded Roles we should ONLY allow existing roles and users. Therefore if the user enters a non existing user or role the following error should show up:

Specified User or Role does not exist.

It should only have an OK button and the user or role should not be added. If possible and does not require a lot of effort we should implement auto complete (there is auto complete in other extensions if I am not mistaken such as the search. Maybe we should check the code and reuse it or create common code to be used by all).

In case of Excluded Custom Fields we should only allow characters that are allowed in custom fields names. Right now I can add characters such as ^ etc. I am checking if there is an official list of characters. Will keep you posted.

**Comment by carmelopreeostudios** [comment]
I left only the last point, let me know about the list of characters

**Comment by robert81** [comment]
@carmelopreeostudios it seems that so far all the characters are allowed, there is no official list. Also auto complete is working so will close this for now. Thank you for the fix.
