### ISSUE TITLE
Alerts 2122 to 2125 should have link to View Tag

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#448]
Alerts 2122 up to 2125 (Except 2122) should have a link in the alert to view the Tag. E.g:

Changed the slug of tag XXX. View the Tag.

The link should link to the Tag view, like we have in alert 2121

**Comment by asharirfan** [comment]
Updated alert 2123, 2124, 2125.
Alert 2122 notifies tag deletion, so the tag will not have a link to post.
