### ISSUE TITLE
Alerts 2046 and 2051 are not working

### ISSUE THREAD

**Issue by asharirfan** [WPWhiteSecurity/WP-Security-Audit-Log#451]
# Issue
Alerts 2046 and 2051 are not working after WP 4.9 update. It is happening because of the enhancement of code editors for WP Themes and Plugins.

**Comment by WPWhiteSecurity** [comment]
@asharirfan ok let's fix them with the next update. No need to release hot patch for this, it is not critical

**Comment by asharirfan** [comment]
This one is not solvable yet because the new update does not contain any hooks to detect changes. I will try and submit a ticket to WordPress Trac for the hooks.

**Comment by WPWhiteSecurity** [comment]
@asharirfan ok no problem. Setting the label **Future** on this one. It is a new label I just created. We can use it to tag such bugs / issues which cannot be addressed now.

**Comment by robert81** [comment]
This was addressed very long ago.
