### ISSUE TITLE
Change (PRO) to an Upgrade Icon

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#452]
Change the (PRO) text in the node for premium functionality to an upgrade icon. The (PRO) is too long so some of the nodes are being wrapped.

Also, Notification Emails should be changed to Email Notifications.

**Comment by asharirfan** [comment]
Which upgrade icon should I use in place of (PRO)?

**Comment by WPWhiteSecurity** [comment]
Let's find something simple such as:

https://png.icons8.com/hotel-upgrade/p1em/1600
https://visualpharm.com/assets/10/Hotel%20Upgrade-595b40b75ba036ed117d62a7.svg
http://www.microspot.com/images/upgradesnav.png

**Comment by asharirfan** [comment]
How about this?

![alt text](https://cl.ly/npRF/💯 "WSAL Menu")

**Comment by WPWhiteSecurity** [comment]
Can we make something a bit more "prominent"?

**Comment by asharirfan** [comment]
Sure. How about these four?

![alt text](https://cl.ly/nqCC/💯 "Icon 1")
![alt text](https://cl.ly/nqIM/💯 "Icon 2")
![alt text](https://cl.ly/nqfe/💯 "Icon 3")
![alt text](https://cl.ly/nqBN/💯 "Icon 4")

**Comment by WPWhiteSecurity** [comment]
Let's go for the second one.
