### ISSUE TITLE
Improvements to Upgrade to Premium Advert in Help Page

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#456]
The **Upgrade to Premium** advert in the help page should be as a "sidebar" rather than at the top, to replace the existing  section "WP Security Audit Log in your language"

Also, the **Upgrade to Premium** button should open the pricing page in the same tab and not in a new tab.

![image](https://user-images.githubusercontent.com/9016202/33011446-eeb93cf2-cdd5-11e7-824d-ed9ea40c3d0c.png)

**Comment by asharirfan** [comment]
Should this disappear from the sidebar when the premium version is active?

**Comment by WPWhiteSecurity** [comment]
yes.
