### ISSUE TITLE
Use the new plugin logo

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#465]
Please implement the new plugin logo in the top advert, in the plugin menu node, in help / about pages etc. 
Logo files: [wsal_logo.zip](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/files/1516881/wsal_logo.zip)

**Comment by WPWhiteSecurity** [comment]
top banner is looking good. Can we use it for the plugin menu node?

**Comment by asharirfan** [comment]
We can use a logo icon in the plugin menu node. You mentioned that you would get a black and white one for this.

**Comment by WPWhiteSecurity** [comment]
Ok will get one from the designer.

**Comment by WPWhiteSecurity** [comment]
B&W logos attached @asharirfan 

[logos.zip](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/files/1543694/logos.zip)
