### ISSUE TITLE
User not reported in alert 2099 (posted new comment)

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/WP-Security-Audit-Log#469]
When a logged in user posts a comment, alert 2099 is not reporting the user but "website visitor". This should be the case when the user is not logged in, but if the user is logged in we should report the user.

**Comment by asharirfan** [comment]
Just checked this issue and here is the result: https://cl.ly/o9wR

**Comment by WPWhiteSecurity** [comment]
@asharirfan it seems that the user is reported only when the built-in administrator account is used. If you use any user account then the username is not being reported. I can reproduce this. Can you?

**Comment by asharirfan** [comment]
If the user is logged in then everything works fine. But when he/she is logged out and use their email address to post comment then this issue occurs. Going to fix it now.
