### ISSUE TITLE
Update text of Alert 1003 in Enable/Disable Alerts section

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#47]
We need to update the text of Alert 1003 in the Enable/Disable alerts section to the following:

Login failed / non existing user

![image](https://cloud.githubusercontent.com/assets/3965050/6551830/eb132ed8-c63e-11e4-8518-2b0490b9b45d.png)

**Comment by carmelopreeostudios** [comment]
done
