### ISSUE TITLE
Log from other plugins

### ISSUE THREAD

**Issue by strarsis** [WPWhiteSecurity/WP-Security-Audit-Log#477]
How can I add WP-Security-Audit-Log logging support to my plugin?

**Comment by WPWhiteSecurity** [comment]
HI @strarsis can you please be more specific?

**Comment by strarsis** [comment]
@WPWhiteSecurity: For example, some plugin does an action on behalf of an user.
This action should be logged in WP Security Audit log. Is there a function in WP Security Audit log plugin that allows other plugins to log an action?

**Comment by WPWhiteSecurity** [comment]
Yes it is possible @strarsis 

We have the custom alerts module for integrations. You can read more about it here: https://www.wpsecurityauditlog.com/support-documentation/create-custom-alerts-wordpress-audit-trail/

Some developers even built their own plugin, such as [WP Security Audit Log addon for Paid Memberships Pro](https://en-gb.wordpress.org/plugins/wp-security-audit-log-for-paid-memberships-pro/).

I hope this answers your question. Should you have any further questions please do not hesitate to ask.
