### ISSUE TITLE
Add transient to improve performance

### ISSUE THREAD

**Issue by nattyait** [WPWhiteSecurity/WP-Security-Audit-Log#478]
Hi,

We are going to use WP security audit log for our multisite. We have more than 1000 sites 
on our network. We found that it slows our sites down so we add this transient code 
to the plugin:

```
+		////// set transient for reduce load on database for check table exits .
+		$wp_wsal_options_status = get_transient( wp_wsal_options_status );
+		if ( “” == $wp_wsal_options_status ) {
+			$wp_wsal_options_status = strtolower( $_wpdb->get_var( $sql ) ) == strtolower( $this->GetTable() );
+			set_transient( wp_wsal_options_status, $wp_wsal_options_status );
+		}
+		return $wp_wsal_options_status;
```

Could you please suggest how can we make this better? We don't want to directly fix 
your code since we are waiting for update in the next version.

Can I submit pull request for this case? Please suggest.

Regards,
Natty

**Comment by WPWhiteSecurity** [comment]
Hello @nattyait 

Thank you very much for pointing out this issue. 

In the next update we will be saving all table names in transients. The next update will be available within a week or two. In the update after next one we will also review the database connector code to make sure we save as much data as we can in transients, to reduce the load on the database and on the server.

I think at this stage the best thing is to modify the plugin's code directly on your website and then it will be overwritten with our code in the next update, which will include the fix.

Please let me know if there is anything else we can help you with and thank you again for your cooperation and for using the plugin.

**Comment by nattyait** [comment]
Thanks!
