### ISSUE TITLE
Filters out all the values when UpdateMenuItem() fires.

### ISSUE THREAD

**Issue by kirtanbodawala** [WPWhiteSecurity/WP-Security-Audit-Log#483]
`$post_array = filter_input_array( INPUT_POST );` returns an empty values. 

For example :

When I print_r($post_array) it gives me 
`Array
(
    [nav-menu-data] => 
    [closedpostboxesnonce] => 1jn3414124
    [meta-box-order-nonce] => 98098090
    [update-nav-menu-nonce] => 54135151
    [_wp_http_referer] => /wp-admin/nav-menus.php
    [action] => update
    [menu] =>1
    [menu-name] => Index
    [save_menu] => Save Menu
    [menu-item-url] => 
    [menu-item-title] => 
    [menu-item-attr-title] => 
    [menu-item-classes] => 
    [menu-item-xfn] => 
    [menu_item_image_size] => 
    [menu_item_image_title_position] => 
    [menu-item-description] => 
    [menu-item-db-id] => 
    [menu-item-object-id] => 
    [menu-item-object] => 
    [menu-item-parent-id] => 
    [menu-item-position] => 
    [menu-item-type] => 
    [menu-locations] => 
)`

But when print_r($_POST), it has all the values filled inside it.

**Comment by WPWhiteSecurity** [comment]
Hello @kirtanbodawala 

Thank you for reaching out. Can you please be more specific on what you are trying to do so we can better assist you?

Looking forward to hearing from you.
