### ISSUE TITLE
GLOB_BRACE is not defined on all platforms

### ISSUE THREAD

**Issue by Mekton** [WPWhiteSecurity/WP-Security-Audit-Log#484]
Hi Team,

I'm using WP:4.9.8 on Alpine:3.7.0 with PHP:7.2.8 and installed WPSAL:3.2.3.2
Just want to report to you that PHP warning message appearing when I'm configuring the WP-Security-Audit-Log plugin just after install : 

> Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/plugins/wp-security-audit-log/classes/Settings.php on line 1250

GLOB_BRACE seems to be used in 3 files : 

classes/Sensors/LogInOut.php:69
classes/Sensors/System.php:106
classes/Settings.php:1250

According to the PHP manual, GLOB_BRACE does not seems to be defined on all platforms (like Alpine) : 

http://php.net/manual/en/function.glob.php#refsect1-function.glob-notes

Here some links for some detailled info & fixes : 

https://github.com/wp-cli/wp-cli/issues/4353
https://github.com/composer/composer/pull/7444

Good continuation ;)

**Comment by WPWhiteSecurity** [comment]
Thanks for reaching out @Mekton 

We will look into this and see how to tackle it. Will get back to you if we need further information.

**Comment by WPWhiteSecurity** [comment]
Hello @Mekton 

We have checked the code and we can confirm that we no longer need GLOB_BRACE so removing it. Releasing a hotfix with other updates later on this week. 

Thank you for using our plugin and please do let us know if there is anything else we can assist you with.
