### ISSUE TITLE
GLOB_BRACE is not supported on musl libc based distros

### ISSUE THREAD

**Issue by arungn-tii** [WPWhiteSecurity/WP-Security-Audit-Log#485]
Our wordpress containers are based on Alpine image which uses musl libc. musl doesn't support GLOB_BRACE. https://bugs.php.net/bug.php?id=72095 . Is there any plan to create a workaround so that WP security audit log plugin does not fill up php error logs with warnings about glob() expecting 2 parameters?

**Comment by WPWhiteSecurity** [comment]
Hello @arungn-tii 

Thank you for using our plugin. Yes we are removing the use of BLOG_BRACE, it is no longer needed. We are releasing an update next week with this fix. Should you have any further queries please do not hesitate to get in touch.
