### ISSUE TITLE
Page or Post?

### ISSUE THREAD

**Issue by hudsantos** [WPWhiteSecurity/WP-Security-Audit-Log#487]
Hi,

I'm translating things here to brazilian portuguese and faced this lines 318 and 319 referencing to 'post page':

[L318](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/blob/cf6b26fa5f7d93576f65b1ec4ce245f58b490e6b/defaults.php#L318)

[L319](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/blob/cf6b26fa5f7d93576f65b1ec4ce245f58b490e6b/defaults.php#L319)

AFAIK it can be or post or page...
How should I proceed?

Thanks,

**Comment by WPWhiteSecurity** [comment]
Thank you for your help with the translation @hudsantos .

That list of event IDs (from line 308 up to line 338) are all obsolete and are there only for backward compatibility. They will be deleted from there within a few months, so do not hassle about translating them. They are for very old versions of the plugin.
