### ISSUE TITLE
Last release cannot be installed via composer

### ISSUE THREAD

**Issue by strarsis** [WPWhiteSecurity/WP-Security-Audit-Log#492]
@asharirfan, @carmelopreeostudios, @uuf6429:
Installing the last release of wp-security-audit-log results in faulty plugin folder: 
It contains `assets/`, `branches/`, `tags/`, `trunk/` but no normal plugin files.

`composer.json`:
```json
"wpackagist-plugin/wp-security-audit-log": "^3.5"
````

The composer packages are installed from wpackagist.org:
https://wpackagist.org/search?q=wp-security-audit-log&type=any&search=

**Comment by WPWhiteSecurity** [comment]
Thank you for reporting this @strarsis , however, we solved this issue quite a few days ago. In fact the directory listing is correct:

https://plugins.svn.wordpress.org/wp-security-audit-log/tags/3.5/

Maybe there is some cache affecting this.
