### ISSUE TITLE
GDPR Typo in Settings > General

### ISSUE THREAD

**Issue by nao360** [WPWhiteSecurity/WP-Security-Audit-Log#503]
GDPR is misspelled as 'GDRP' in Settings > General.

Happy to clone the repo, branch and rise a PR with the correction if it helps. Otherwise, the typo is on line 784 in `languages/wp-security-audit-log.pot`

Screenshot:
![image](https://user-images.githubusercontent.com/6898065/71191887-2da1f080-227f-11ea-9d88-304382e6421a.png)

**Comment by WPWhiteSecurity** [comment]
Thank you for reporting this @nao360 

No need to rise a PR. Will fix it with the next update. Appreciate the effort. Have a great day and thank you for using our plugin.

**Comment by pattonwebz** [comment]
Hey Nao, I have included [a commit in the next release](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/commit/d83390e3c8cbc238d388f2d0acc2b99781db51e0) that corrects this. Thank you for pointing it out.

**Comment by nao360** [comment]
Hi William,

Just saw the commit -- looking forward to the update, and thanks for the mention.

Nao
