### ISSUE TITLE
Should yoast seo events/Woocommerce event be active by default

### ISSUE THREAD

**Issue by DannyWPWS** [WPWhiteSecurity/wp-security-audit-log#519]
When installing yoast or woocommerce, I need to activate the events before I see them in the log

This seems like a pain, we should "enable" these events at the point of activation of the plugin in question.

**Comment by DannyWPWS** [comment]
Labelling this as a bug now as iv just reset my site to retest for #520, activating JUST WSAL and WooCommerce, and the events are enabled, so something is causing a bug here.

Worth investigating in future but wont dwell on it now.

**Comment by WPWhiteSecurity** [comment]
I am going to close this issue for now. This will be addressed / obsolete once we separate Yoast SEO and WooCommerce from the main plugin.
