### ISSUE TITLE
Duplicate Options in Plugins settings

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#52]
Issue reported here: https://wordpress.org/support/topic/refresh-audit-view-refresh-audit-log-viewer?replies=2#post-6708853

In the plugin settings there are the following 2 options which have the same effect.

Refresh Audit View

Refresh Audit Log Viewer

The option Refresh Audit View should be remove as it is duplicate.

**Comment by robert81** [comment]
@carmelopreeostudios @markdelf for some reason some of the settings are duplicate, and not just the ones mentioned above. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/3965050/6727761/dd514968-ce24-11e4-9baa-722aa9ccafa0.png)

**Comment by carmelopreeostudios** [comment]
@robert81 Removed

**Comment by robert81** [comment]
@carmelopreeostudios @markdelf  the option "Hide Plugin in Plugins Page" is still duplicate. Let's make sure such simple fixes are double checked before committed.

**Comment by carmelopreeostudios** [comment]
@robert81 It is removed
