### ISSUE TITLE
WooCommerce - Cant trigger 9000 (product published)

### ISSUE THREAD

**Issue by DannyWPWS** [WPWhiteSecurity/wp-security-audit-log#520]
Currently the event is enabled but its not firing at all, no errors. Will update after a little more testing (going to reset my site again and try once more)

**Comment by DannyWPWS** [comment]
Can confirm this is still an issue on a fresh site, but all other 9002 onward appear fine, but will update if I find more

**Comment by DannyWPWS** [comment]
Same on multisite also

**Comment by DannyWPWS** [comment]
Sorted :) 

![image](https://user-images.githubusercontent.com/59394454/82663995-b7882800-9c28-11ea-90f1-447424e63432.png)

Only a slight tweak needed thankfully

**Comment by WPWhiteSecurity** [comment]
This is working now. However, after event ID 9000 (when a user saves a product as draft) upon the refresh of the page the plugin reports event ID 9072 (user opened the product page). This event should not be triggered since this is just occurring because of a page refresh.
