### ISSUE TITLE
Problems with Database

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#54]
@markdelf @carmelopreeostudios 

It seems in version 1.5 there are several users which are having problems. While one of them reported that the options table was not created:

https://wordpress.org/support/topic/wp_wsal_options-not-created-with-plugin-update?replies=6

Another one is saying that none of the tables are being created:

https://wordpress.org/support/topic/missing-database-tables-1?replies=9

Another user reported that the options table was not created though he deactivated and activated the plugin again and the table was created. 

Considering there are already 3 tickets related to this issue it seems this can be a "generic" problem. Let's created a debug version of the plugin where it creates its own logs (or something similar) and log everything that is happening during activation, especially the database activity. We need to identify why the table is not being created, maybe we are getting a timeout from the SQL or something similar.

Can you please create this debug version so I send it to the customers with the problem?

**Comment by carmelopreeostudios** [comment]
@robert81 Yes, when you upgrade the plugin doesn't creates the tables, so now the table is created on load if doesn't exist

**Comment by robert81** [comment]
@carmelopreeostudios this is very strange as I remember testing this myself and it was working. In fact we had some problems with the multisite upgrade and we had fixed it (there were some issues for it). It seems that something went wrong between the merging / uploading process and all. Well now 1.5.1. seems to be working well.
