### ISSUE TITLE
this plugin killed my clients site

### ISSUE THREAD

**Issue by rtpHarry** [wpwhitesecurity/wp-security-audit-log#608]
Just thought I would give you a heads up to consider some kind of helper feature here.

The clients site uses https://www.wppropertyfeed.co.uk/

This plugin continually syncs a feed of data into the site, into a cpt.

The site used a default install of wp-activity-log.

It logged every change to the feed data. 

After a year, the log table was 1gb, the site hit the hosting limits, and then the whole thing fell to bits.

This is just a heads up, I'm not looking for support, I just removed the plugin as we have never used the activity log functionality.

But I thought you might be interested though as an edge case for some kind of automated notification when the tables are getting big, or if there is a feature in there that culls it, then suggest culling it to the admin. I had no idea the table was growing that big until the hosting companies systems kicked in and forced me to look at what was going on.

**Comment by robert81** [comment]
For the plugin to check the database table size would require a lot of resources. In this case one should [configure the activity log retention policies](https://melapress.com/support/kb/wp-activity-log-retention-policies/).
