### ISSUE TITLE
Audit Log Viewer not working on WP Engine Install

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#61]
@carmelopreeostudios on a WP Engine install the Audit Log Viewer is not working, i.e. the plugin logs alerts and work normally though when users access the Audit Log Viewer they get a blank page.

WP Engine support said the following "an error 500 (trying to make the server do something that isn't allowed, essentially). I've traced it back to the Render() method for the AbstractClass."

One user gave us access to a staging website of his to test the installation. Will send you the credentials via email so we can test this and fix it for 1.5.2.

**Comment by robert81** [comment]
It seems issue is only reproduced on multisite. Will wait for WP Engine or customer to provide us with test account, so for now there is no need to do anything.

**Comment by joseforland** [comment]
noted @robert81 - will wait for more feedback before we action this bug.

**Comment by robert81** [comment]
Will close this for now as on default installs of WP Engine the plugin is working, hence this is an issue which is related to other third party components.

**Comment by robert81** [comment]
Closing for now as this is a specific issue, i.e. the plugin works on default WP Engine installation (both single and multisite)
