### ISSUE TITLE
Error on ViewManager.php

### ISSUE THREAD

**Issue by elarion83** [wpwhitesecurity/wp-security-audit-log#673]
Hi,

I'm encountering this issue with your plugin : 

Warning: Undefined array key "page" in /var/app/current/web/app/plugins/wp-security-audit-log/classes/ViewManager.php on line 381

Here is the line 381 : 
`if ('admin.php' === $pagenow && 'wsal-auditlog-pricing' === $_GET['page'] ) { // phpcs:ignore
`

Apparently just adding this condition : `isset($_GET['page']` solve the problem.

**Comment by robert81** [comment]
This has been fixed in previous versions of the plugin. Please update the plugin to the latest version.
