### ISSUE TITLE
No alerts generated for when multiple plugins are updated at the same time

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#68]
@carmelopreeostudios When there are multiple plugins that need to be upgraded and they are upgraded all at once (plugins screen -> tick box next to each -> drop down menu "update") no alert is being generated.

In such case we should generate an alert for each upgrade.

**Comment by carmelopreeostudios** [comment]
@robert81 I tested this issue on develop branch and seems working fine

**Comment by robert81** [comment]
@carmelopreeostudios with the release of WordPress 4.2 I can confirm that this is not working.

**Comment by robert81** [comment]
@carmelopreeostudios this is still not fixed. Just to confirm how to reproduce:

1. Install 2 plugins. Use an older version not the latest version of each.
2. From the plugins screen tick the check box next to each button
3. From the drop down menu select "update" and click "Apply".

No alerts are generated at this point.

**Comment by robert81** [comment]
confirmed and fixed
