### ISSUE TITLE
Date / Time column should have a better format / spacing + New timing option

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#69]
At the moment all the entries in the Date column have an additional line just for the "M" of AM or "PM", as highlighted in the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/3965050/7112748/3d15635a-e1cd-11e4-9df1-dc595433af46.png)

This should be fixed by widening a bit the column to ensure it all fits in 1 line.

We should also add a new option in the settings so the user can select to use the current time system or 24 hours format. The setting should be added above the Developer options and should have the following text and radio box options:

Alerts Time Format:  24 hours   AM/PM

**Comment by carmelopreeostudios** [comment]
Fixed on the commit 3fdc826009a6f19da1c1963f7a3e4ca2c778e544

**Comment by robert81** [comment]
confirmed it is fixed.
