### ISSUE TITLE
Adminer plugin - no alerts generated for any actions

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#72]
I installed the Adminer plugin (https://wordpress.org/plugins/adminer/) and can confirm that if I create a new table, modify it or delete it, or modify an existing table no new alerts are being generated (e.g. added table etc).

Can we check what this plugin is using, i.e. if it is using standard WordPress functions to do such tasks and confirm if we should be able to monitor its activity?

**Comment by robert81** [comment]
By the way here is some codex that might come in handy; https://codex.wordpress.org/Creating_Tables_with_Plugins

**Comment by carmelopreeostudios** [comment]
@robert81 This plugin using custom php code and there is not reference with wordpress hooks for monitoring its activity
