### ISSUE TITLE
No database changes alerts generated in multisite - Develop Branch

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#74]
Testing the develop branch -

When I install a plugin such as WooCommerce or Easy Digital Downloads on multisite the database changes (added table, deleted table) are not showing up. This was working in the 1.6.0 branch.

**Comment by carmelopreeostudios** [comment]
@robert81 I tested in the develop branch and seems work fine, but now the plugin doesn't showing the alert if the table already exist, so you have to drop the table before activate again for see the alert

**Comment by robert81** [comment]
Strange, I must have screwed up something. Well now all is working.
