### ISSUE TITLE
Check usage of add_query_arg()

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#80]
There are a number or problems regarding the usage of add_query_arg() as explained here:

https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/

We use this function in our licensing module (classes/LicenseManager.php).

Can we please check that all of the correct escaping is in place?

**Comment by carmelopreeostudios** [comment]
Hi Robert,
about the issue #80 I added the escaping, but I'm not sure how to test it,
is it used in the others plugins?

Regards,
Carmelo

On 21 April 2015 at 16:56, Robert Abela <notifications@github.com> wrote:

> Assigned #80
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/80> to
> @carmelopreeostudios <https://github.com/carmelopreeostudios>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/80#event-286302904>
> .
>



-- 

*Carmelo Cutrera*
Web developer

*Mobile: *00356 99664357

*Office: *Entrance C, Level 2, Capital Business Centre, Zwejt Street, San
Gwann, SGN 3000. Malta
*Web:* www.preeostudios.com

<http://www.preeostudios.com/>

**Comment by robert81** [comment]
There are WordPress plugins such as WordPress SEO that did such fix (https://yoast.com/coordinated-security-release/). Can you download the previous release, new release and compare what they did so we do something similar?

You can download previous versions of the plugin from here: https://wordpress.org/plugins/wordpress-seo/developers/.

I am assigning this ticket to milestone 1.6.1 so we can release an update once t his is ready. Can you please drop me an email once you are ready with this?

**Comment by carmelopreeostudios** [comment]
Hi Robert,
I downloaded the wordpress Seo plugin and I did the same changes their did,
I think should be work
but can you explain me how to test the code just for make sure the code
doesn't break.
Thanks

Regards,
Carmelo

On 22 April 2015 at 16:58, Robert Abela <notifications@github.com> wrote:

> There are WordPress plugins such as WordPress SEO that did such fix (
> https://yoast.com/coordinated-security-release/). Can you download the
> previous release, new release and compare what they did so we do something
> similar?
>
> You can download previous versions of the plugin from here:
> https://wordpress.org/plugins/wordpress-seo/developers/.
>
> I am assigning this ticket to milestone 1.6.1 so we can release an update
> once t his is ready. Can you please drop me an email once you are ready
> with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/80#issuecomment-95221752>
> .
>



-- 

*Carmelo Cutrera*
Web developer

*Mobile: *00356 99664357

*Office: *Entrance C, Level 2, Capital Business Centre, Zwejt Street, San
Gwann, SGN 3000. Malta
*Web:* www.preeostudios.com

<http://www.preeostudios.com/>

**Comment by robert81** [comment]
closed in version 1.6.1
