### ISSUE TITLE
Plugin Upgrades not being reported

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#84]
In WordPress 4.2 the plugin updates system has changed hence plugin updates are not being reported. Can we please look into this and fix it ASAP?

**Comment by robert81** [comment]
For this fix let's make sure we have backward compatibility with previous versions of WordPress (At least the 4.x versions).

**Comment by carmelopreeostudios** [comment]
Good morning Robert,
I'm sorry for the late reply, I'll work on this issue tomorrow or Wednesday
if it is
not very urgent.

Regards,
Carmelo
