### ISSUE TITLE
Plugin Upgrades through third party InfiniteWP Not Logged

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#93]
When upgrading a plugin through InfiniteWP no alert 5004 (updated plugin) is being reported. It could be that infiniteWP are using a different method. Considering this service / application is pretty popular we should support it.

Below is a URL for a ticket about it and I can reproduce the issue:

https://wordpress.org/support/topic/updating-plugins-via-infinitewp-does-not-log-in-wsal?replies=3#post-6960706

**Comment by WPWhiteSecurity** [comment]
As agreed we will close this issue.
